BHoM/Python_Toolkit

Python_Engine/Compute/CopyEmbeddedResourceToFile.cs, Python_Engine/Compute/Install.cs, Python_PostBuild/App.config, Python_PostBuild/Program.cs, Python_PostBuild/Properties/AssemblyInfo.cs, Python_PostBuild/Python_PostBuild.csproj, Python_Toolkit.sln
Closes #1 
The test is done by just compiling the application and checking the `AppData/Roaming/BHoM` directory contains a `python-3.7.3-embed-amd64` folder. Then, it can be tested in tandem with this pr https://github.com/BHoM/Keras_Toolkit/pull/14. `LoadImg` is a simple function to test.
- Centralise the python local installation to `AppData/Roaming/BHoM`
- Add PostBuild events to install python at compile time
- Add the possibility to install modules from post build events
@FraserGreenroyd this pr does not have labels because they are not set for this repo. 
I will raise an issue for that, would it be ok to pick it up?
@MarthaVoul I added you to this pull request just to start familiarising with what is happening on the framework side. I do not expect you to pick up the review, but you …
=> Centralise python resource to AppData/Roaming/BHoM

Python_Engine/Compute/Install.cs, Python_PostBuild/Program.cs, pyBHoM/__init__.py, setup.py
Closes #15
You can open grasshopper, run the `Jupyter` component that opens a new jupyter notebook and use the following code.
This is an example of how to use a `BHoMAdapter` from python:
```python
import pyBHoM, BH
import os
import System
filepath = os.path.join(os.getenv("HOME"), "Desktop", "pyBHoM_test")
file_adapter = BH.Adapter.FileAdapter.FileAdapter(filepath)
objects = System.Array[System.Object]([BH.Engine.Acoustic.Create.RT60(1., 1, 10)])
pushed = file_adapter.Push(objects)
pulled = file_adapter.Pull(None)
for item in pulled:
print(item.get_ReceiverID())
print(item.get_SpeakerID())
print(item.get_Value())
print("---")
```
And you get your `BH.oM.Acoustic.RT60` object. This works with any other python object.
=> Add ability to use the BHoM API from python

Python_Engine/Compute/Install.cs, Python_Engine/Compute/InstallPythonToolkit.cs, Python_Engine/Compute/Invoke.cs, Python_Engine/Python_Engine.csproj, Python_Engine/Query/EmbeddedPythonHome.cs, Python_PostBuild/Program.cs, Python_Toolkit.sln
Fixes #5 
[Very basic file](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Python_Toolkit/InstallTesting.gh?csf=1&web=1&e=G01pIf)
This updates the toolkit for using ProgramData, and removing PostBuild to allow install via Grasshopper/Dynamo/Excel.
As you can see from the file, this should allow Python Toolkit to install correctly from the UI side rather than relying on the post build. I have removed the postbuild from the SLN file but kept it within the repo for now until we're happy.
Things to test:
- Installing and running existing Python Toolkit scripts (@epignatelli is probably best placed for that but view other PRs for help)
- Installing Python and then deleting the folder from `C:\ProgramData\BHoM` and force installing - folder should …
=> Initial commit of changes to ProgramData

Python_Engine/Compute/Install.cs, Python_Engine/Compute/InstallPythonToolkit.cs, Python_Engine/Compute/RunCommand.cs
Closes #19 
While using the `InstallPythonToolkit` method, the command was run asynchronously, but wasn't terminated properly at the end of the task.
https://burohappold.sharepoint.com/:f:/s/BHoM/EvsJ6ZHhETJGpHYIhzPkT_4B2sef9ChpZm-zKGhLBlp6qQ?e=pEk1sN
in the `PythonToolkit#19-FixHangingTasks` folder
- `Compute.Install` now runs synchronously
- `Compute.Install` now returns a boolean of success
- Any `RunCommand` now also `exit` at the end of execution
=> Fix hanging tasks

Python_Engine/Compute/InstallPython.cs, Python_Engine/Compute/InstallPythonToolkit.cs, Python_Engine/Compute/Invoke.cs, Python_Engine/Python_Engine.csproj, Python_Engine/Query/Import.cs, Python_Engine/Query/IsInstalled.cs
Closes https://github.com/BHoM/MachineLearning_Toolkit/pull/19
This pr support https://github.com/BHoM/MachineLearning_Toolkit/pull/19 by fixing the path to python.
The issue was that, if you have another python installation on your machine, and the BHoM Python is not installed, the application would crash completely.
We solve by removing the reference to the `PATH` completely, and adding it on the fly.
Our usual https://burohappold.sharepoint.com/:f:/s/BHoM/EmYIW2WfjUtPkIYccZ-8V8gBZTOmUfLfgK1gllazCEilcQ?e=dprvsm
- Rename `Query.IsIntalled` to `Query.IsPythonInstalled`
- Fix `Copy Local`s and set them to `False`
- PythonPath is not registered anymore at installation time and user level environment variable. We now set it to process level at runtime.
- Make sure that the installed modules …
=> Separate the Python program for the BHoM from potential existing Python installations

Python_Engine/Compute/InstallPython.cs
Closes #35
We have been adding `C:\ProgramData\BHoM\python-3.7.3-embed-amd64` to the `PATH`, but this is not required and can potentially lead to conflicts with other python installations.
1. Remove `C:\ProgramData\BHoM\python-3.7.3-embed-amd64` from your PATH Environment variable
2. Remove the entire `C:\ProgramData\BHoM\python-3.7.3-embed-amd64` folder
3. Compile the toolkit
4. Open Grasshopper and run `InstallPythonToolkit`
5. Restart Rhinoceros
6. Try to `Import` the `Python_Engine.Compute` module
=> Do not add the BHoM-PythonHome to the PATH Environment variable

Python_Engine/Convert/FromPython.cs, Python_Engine/Convert/ToPython.cs, Python_Engine/Python_Engine.csproj, Python_Engine/Query/Import.cs, Python_Engine/Query/IsInstalled.cs
Depends on: https://github.com/BHoM/MachineLearning_Toolkit/pull/50
Closes #27 
Closes #37
Ok, so this is definitely improving the UX in my opinion. 
We automatically detect if python is installed and if not, we create a pop up and ask for the installation.
1. Remove the `C:\ProgramData\BHoM\Extensions` folder
2. Compile the Python_Toolkit
2. Compile the MachineLearning_Toolkit at this pr https://github.com/BHoM/MachineLearning_Toolkit/pull/50
3. Open this: https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/MachineLearning_Toolkit/MachineLearning%235-LinearRegression/MachineLearning%235-LinearRegression.gh?csf=1&web=1&e=lt2tVa
=> Automatically install python if missing

Python_Engine/Query/IsInstalled.cs
Closes #48 
Necessary adjustment to enable lazy import of modules. Please refer https://github.com/BHoM/MachineLearning_Toolkit/pull/62 for more details.
- Adjust module check for Python and MachineLearning toolkits
=> Fix module check for lazy import

Python_Engine/Compute/BasePythonEnvironment.cs
Added a check prior to installing the Base Python environment that creates a `C:\ProgramData\BHoM\Extensions\PythonEnvironments` directory if it doesn't already exist. This _should_ be handled upon BHoM install, but in-case it's missed this is a failsafe.
Run BasePythonEnvironment on a machine without a `C:\ProgramData\BHoM\Extensions\PythonEnvironments` directory, and no error should occur.
=> Ensure PythonEnvironments exists prior to installation of base environment

Python_Engine/Python_Engine.csproj, Python_Engine/Query/Directory.cs, Python_Engine/Query/VirtualEnvironment.cs, Python_oM/Python_oM.csproj
Closes #125 
Removed all mention of C:\ProgramData in favour of environment variables where possible, and added means of checking existing virtual Python env versions against a target version number.
=> Added version check to existing environment query

Python_Engine/Query/Version.cs, Python_Engine/Query/VirtualEnvironment.cs
Closes #127 
Added a check for if the executable it is trying to run actually exists before running.
run LBT environment installer in grasshopper.
=> Fixed VirtualEnvironmentExists

Python_Engine/Compute/BasePythonEnvironment.cs
Closes #130 
added a boolean "run" to BasePythonEnvironment, and added `PreviousVersion` and `Input` attributes.
place a BasePythonEnvironment component on the canvas and input a bool into run. Test that setting Run to true returns the Python environment.
=> Engine: BasePythonEnvironment boolean run

Python_Engine/Compute/BasePythonEnvironment.cs, Python_Engine/Compute/InstallPackage.cs, Python_Engine/Compute/RequirementsTxt.cs, Python_Engine/Compute/VirtualEnvironment.cs, Python_Engine/Query/Version.cs
Closes #137 
Moved reading standard error and standard output to before waiting for exit on process.
Turns out this was seen before, if you look at `RunCommandStdOut`, there is a comment that says to read stdout and stderr before waiting to exit to avoid deadlocks, but it must have been missed for the other methods. 🤦 
not very easy to test all of these, though InstallPackageLocal should be enough to prove that it works (as that is where the error was originally). do not merge unless @albinber has tested that it is fixed.
=> Fixed deadlock on waiting for exit on some processes

.ci/BHoMBot/Nuget/BHoM.Interop.Python.nuspec
Closes #146 
See the [nuspec file for LadybugTools_Toolkit](https://github.com/BHoM/LadybugTools_Toolkit/blob/develop/.ci/BHoMBot/Nuget/BHoM.Interop.LadybugTools.nuspec) as an example and compare to changes made here.
As python bhom analytics now exists in Python_Toolkit code, this must be included in the nuspec content files as well.
(not to mention future additions to Python_Toolkit python code)
Likely will have to merge this then see if the bot produces nugets that contain the python files first
=> Add python code to nuspec as content files

Python_Engine/Python/src/python_toolkit/plot/heatmap.py
Previously, a mask did not render correctly when blocking out parts of a heatmap. This fix applies a pivot to the mask to match the pivot applied to the heatmap data, and should now produce a masked plot correctly. 
Closes #154
=> Mask pivots correctly when applied to heatmap

Python_Engine/Python/src/python_toolkit/bhom/analytics.py
Closes #149 
Analytics logger updated so that the correct log file names are used for specific toolkits.
Any downstream console loggers must be created in their respective toolkits and inherit from this toolkits logger as a parent (so that log file handling works properly).
See LadybugTools_Toolkit PR for how to do this.
This shouldn't affect any unit tests, but run them just in case. For testing with downstream, use the LadybugTools_Toolkit PR and run a method that calls bhom_analytics and the CONSOLE_LOGGER for that toolkit (I suggest doing a test external comfort study)
=> Correctly log downstream toolkit names when logging for analytics

Python_Engine/Python/src/python_toolkit/plot/heatmap.py, Python_Engine/Python/src/python_toolkit/plot/utilities.py, Python_Engine/Python/tests/test_plot.py, Python_Engine/Python/tests/test_plot_utilities.py
Closes #165
also fix incorrect type for heatmap mask.
run 'run_tests.bat' and ensure all tests pass.
Known issue: sometimes the test fails and provides a tcl error. If this occurs on `test_heatmap` or `test_figure_round_trip`, then ignore this and re-run the test, if it occurs on any other test then it can be ignored.
The tcl error seems to be some sort of weird issue where tkinter can't find itself, even if it does exist - but only when using the pytest module.
=> Fixed missing import and added tests for base64 image encode/decode

Python_Engine/Python/src/python_toolkit/plot/heatmap.py
Closes #167
see the linked issue
Run the heatmap with a series that has some null values in the middle
=> Fix heatmap error when some values in the input series are null

Python_Engine/Python/tests/__init__.py
Closes #169 
As in title, doing `mpl.use("agg")` in the test folders' `__init__.py` file.
Basically what was happening was tkinter is failing seemingly randomly when using pytest citing that one of its libraries/modules is missing even when it isn't. So switch to "agg" backend as we're not testing whether tkinter works, we're testing that the plot can be created.
run the unit tests, and see that there are no failing plot tests.
If there are any failing tests for other reasons, then please comment to be tackled in a separate issue
=> Use agg when testing plot methods

Python_Engine/Python/src/python_toolkit/bhom/analytics.py, Python_Engine/Python/src/python_toolkit/bhom/logging/file.py
Closes #171
Manually edit today's python_toolkit log file to be >25Mb. Then run a Python action that appends to the log file (I created an ExternalComfort object in LBT_TK). The action should run successfully. The log file should be renamed to `f<filename>.log.1` and a new log file with `<filename.>log` should be created in the same log folder. 
The log folder is here: C:\ProgramData\BHoM\Logs
=> Log file paths converted to string to comply with logging parameter types

Python_Engine/Query/Directory.cs
Closes #184 
see linked issue
try running `Query.VirtualEnvironmentExists` with `LadybugTools_Toolkit` while that python env is installed, and ensure that it returns true.
oops, the branch name references the wrong issue :D
=> Fixed incorrect kernel directory location check
